In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("dataset/weight-height.csv")
df

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [42]:
x = df.drop(columns="Gender")
y = df.Gender
y

0         Male
1         Male
2         Male
3         Male
4         Male
         ...
9995    Female
9996    Female
9997    Female
9998    Female
9999    Female
Name: Gender, Length: 10000, dtype: object

In [35]:
x

         Height      Weight
0     73.847017  241.893563
1     68.781904  162.310473
2     74.110105  212.740856
3     71.730978  220.042470
4     69.881796  206.349801
...         ...         ...
1995  66.659493  182.746514
1996  72.610469  216.590561
1997  67.006480  197.799300
1998  69.667115  192.558899
1999  65.078524  174.743510

[2000 rows x 2 columns]

In [49]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, stratify=y, random_state=42)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6700, 2), (3300, 2), (6700,), (3300,))

In [60]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

KNeighborsClassifier()

In [61]:
model.score(X_train, y_train), model.score(X_test, y_test)

(0.9311940298507463, 0.9054545454545454)

### Cross Validation

In [62]:
from sklearn.model_selection import cross_val_score
import numpy as np

In [63]:
knn_cross = KNeighborsClassifier(n_neighbors=3)

cv_Scores = cross_val_score(knn_cross, x, y, cv=6)

print(cv_Scores)
print('cv_scores mean:{}'.format(np.mean(cv_Scores)))

[0.9010198  0.910018   0.895021   0.895021   0.90636255 0.90756303]
cv_scores mean:0.902500892378547

### Hyperparameter Tunning

In [64]:
from sklearn.model_selection import GridSearchCV

In [67]:
n_neighbors = range(1, 50, 2)
p=[1,2]

hyperparameters = dict(n_neighbors=n_neighbors, p=p)
knn_2 = KNeighborsClassifier()
clf = GridSearchCV(knn_2, hyperparameters, cv=3, n_jobs=-1, verbose=1 )
clf.fit(x,y)

Fitting 3 folds for each of 50 candidates, totalling 150 fits

GridSearchCV(cv=3, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'n_neighbors': range(1, 50, 2), 'p': [1, 2]},
             verbose=1)

In [68]:
pd.DataFrame(clf.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_p,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.033665,0.012283,0.427666,0.017461,1,1,"{'n_neighbors': 1, 'p': 1}",0.876125,0.869787,0.873687,0.873200,0.002610,49
1,0.040333,0.007409,0.444666,0.016977,1,2,"{'n_neighbors': 1, 'p': 2}",0.876125,0.867387,0.874587,0.872700,0.003809,50
2,0.038665,0.009843,0.425000,0.018493,3,1,"{'n_neighbors': 3, 'p': 1}",0.907319,0.894389,0.901290,0.900999,0.005282,47
3,0.030333,0.009672,0.412333,0.007364,3,2,"{'n_neighbors': 3, 'p': 2}",0.905819,0.893489,0.899790,0.899699,0.005034,48
4,0.045999,0.016573,0.371333,0.021639,5,1,"{'n_neighbors': 5, 'p': 1}",0.912418,0.900390,0.909091,0.907299,0.005071,45
5,0.035998,0.016971,0.428333,0.033669,5,2,"{'n_neighbors': 5, 'p': 2}",0.911518,0.900990,0.909091,0.907200,0.004501,46
6,0.043333,0.014659,0.370333,0.015063,7,1,"{'n_neighbors': 7, 'p': 1}",0.912717,0.906691,0.913591,0.911000,0.003068,44
7,0.029666,0.004110,0.420429,0.041565,7,2,"{'n_neighbors': 7, 'p': 2}",0.913617,0.907591,0.914191,0.911800,0.002985,43
8,0.020826,0.007362,0.416535,0.032099,9,1,"{'n_neighbors': 9, 'p': 1}",0.912418,0.909991,0.917192,0.913200,0.002991,42
9,0.020825,0.007365,0.395705,0.026549,9,2,"{'n_neighbors': 9, 'p': 2}",0.913017,0.912091,0.915692,0.913600,0.001526,40
10,0.026033,0.007364,0.463392,0.019479,11,1,"{'n_neighbors': 11, 'p': 1}",0.916017,0.909691,0.917792,0.914500,0.003477,28
11,0.031239,0.000005,0.426946,0.014727,11,2,"{'n_neighbors': 11, 'p': 2}",0.915417,0.909391,0.917192,0.914000,0.003339,37
12,0.052063,0.014725,0.359261,0.022087,13,1,"{'n_neighbors': 13, 'p': 1}",0.916017,0.909091,0.917192,0.914100,0.003574,36
13,0.041656,0.014730,0.437356,0.055595,13,2,"{'n_neighbors': 13, 'p': 2}",0.914817,0.910591,0.917192,0.914200,0.002730,35
14,0.046011,0.020888,0.391850,0.030601,15,1,"{'n_neighbors': 15, 'p': 1}",0.916317,0.909991,0.919292,0.915200,0.003878,13
15,0.031207,0.003938,0.430015,0.024341,15,2,"{'n_neighbors': 15, 'p': 2}",0.916017,0.911191,0.918392,0.915200,0.002996,12
16,0.041654,0.014726,0.385292,0.048285,17,1,"{'n_neighbors': 17, 'p': 1}",0.915717,0.910891,0.918992,0.915200,0.003327,10
17,0.020827,0.007362,0.421738,0.067486,17,2,"{'n_neighbors': 17, 'p': 2}",0.917516,0.910591,0.918392,0.915500,0.003489,5
18,0.036443,0.019478,0.374880,0.071011,19,1,"{'n_neighbors': 19, 'p': 1}",0.916317,0.909091,0.917792,0.914400,0.003802,31
19,0.036446,0.019481,0.400911,0.070241,19,2,"{'n_neighbors': 19, 'p': 2}",0.916317,0.909091,0.917792,0.914400,0.003802,31
20,0.041650,0.014727,0.411328,0.053096,21,1,"{'n_neighbors': 21, 'p': 1}",0.917217,0.909091,0.920792,0.915700,0.004896,2
21,0.036449,0.007363,0.416533,0.051543,21,2,"{'n_neighbors': 21, 'p': 2}",0.914817,0.908791,0.919292,0.914300,0.004303,33
22,0.032306,0.013979,0.460111,0.045489,23,1,"{'n_neighbors': 23, 'p': 1}",0.916617,0.908791,0.920192,0.915200,0.004761,14
23,0.042009,0.015634,0.436016,0.037820,23,2,"{'n_neighbors': 23, 'p': 2}",0.915417,0.908491,0.919592,0.914500,0.004578,27
24,0.039702,0.011970,0.473598,0.057267,25,1,"{'n_neighbors': 25, 'p': 1}",0.914517,0.908191,0.919892,0.914200,0.004782,34
25,0.036447,0.019483,0.390497,0.067485,25,2,"{'n_neighbors': 25, 'p': 2}",0.916617,0.907591,0.919292,0.914500,0.005006,29
26,0.031239,0.022085,0.416530,0.084918,27,1,"{'n_neighbors': 27, 'p': 1}",0.915417,0.908491,0.920492,0.914800,0.004919,21
27,0.041652,0.007361,0.406119,0.033742,27,2,"{'n_neighbors': 27, 'p': 2}",0.915417,0.909091,0.920792,0.915100,0.004782,15
28,0.052064,0.007365,0.473807,0.044789,29,1,"{'n_neighbors': 29, 'p': 1}",0.916017,0.907891,0.920792,0.914900,0.005326,18
29,0.041650,0.019478,0.416534,0.103873,29,2,"{'n_neighbors': 29, 'p': 2}",0.914817,0.908491,0.920192,0.914500,0.004782,26
30,0.026034,0.007364,0.458187,0.032094,31,1,"{'n_neighbors': 31, 'p': 1}",0.915417,0.907291,0.919292,0.914000,0.005001,37
31,0.026030,0.014727,0.437358,0.038259,31,2,"{'n_neighbors': 31, 'p': 2}",0.915717,0.909091,0.919592,0.914800,0.004336,22
32,0.036446,0.019478,0.426945,0.081994,33,1,"{'n_neighbors': 33, 'p': 1}",0.915417,0.907291,0.918092,0.913600,0.004593,41
33,0.026034,0.007362,0.432152,0.065448,33,2,"{'n_neighbors': 33, 'p': 2}",0.916017,0.908791,0.919292,0.914700,0.004387,23
34,0.036449,0.019482,0.421737,0.063768,35,1,"{'n_neighbors': 35, 'p': 1}",0.915717,0.907891,0.918392,0.914000,0.004456,39
35,0.041651,0.014729,0.395707,0.070244,35,2,"{'n_neighbors': 35, 'p': 2}",0.914817,0.909391,0.920192,0.914800,0.004410,20
36,0.052066,0.014724,0.437357,0.077577,37,1,"{'n_neighbors': 37, 'p': 1}",0.916317,0.908491,0.918392,0.914400,0.004263,30
37,0.040825,0.013558,0.429893,0.143360,37,2,"{'n_neighbors': 37, 'p': 2}",0.916317,0.908791,0.920792,0.915300,0.004952,7
38,0.052068,0.014725,0.432152,0.074731,39,1,"{'n_neighbors': 39, 'p': 1}",0.915717,0.909691,0.920192,0.915200,0.004303,10
39,0.031239,0.012751,0.426944,0.084917,39,2,"{'n_neighbors': 39, 'p': 2}",0.916317,0.908491,0.918992,0.914600,0.004456,24
40,0.020827,0.007365,0.432153,0.070242,41,1,"{'n_neighbors': 41, 'p': 1}",0.914517,0.910591,0.920492,0.915200,0.004071,9
41,0.041649,0.014727,0.416531,0.058908,41,2,"{'n_neighbors': 41, 'p': 2}",0.916617,0.908791,0.919592,0.915000,0.004555,17
42,0.036448,0.019482,0.426945,0.062911,43,1,"{'n_neighbors': 43, 'p': 1}",0.914817,0.910291,0.921392,0.915500,0.004558,3
43,0.041653,0.007363,0.439365,0.053877,43,2,"{'n_neighbors': 43, 'p': 2}",0.916617,0.908791,0.918392,0.914600,0.004171,25
44,0.031238,0.012753,0.458185,0.019480,45,1,"{'n_neighbors': 45, 'p': 1}",0.915117,0.909691,0.921392,0.915400,0.004781,6
45,0.046860,0.022091,0.452977,0.055591,45,2,"{'n_neighbors': 45, 'p': 2}",0.917217,0.910291,0.918392,0.915300,0.003574,8
46,0.031240,0.000002,0.442565,0.051544,47,1,"{'n_neighbors': 47, 'p': 1}",0.916017,0.910591,0.920792,0.915800,0.004167,1
47,0.031237,0.012753,0.447772,0.073632,47,2,"{'n_neighbors': 47, 'p': 2}",0.916317,0.909091,0.919292,0.914900,0.004283,19
48,0.026031,0.007361,0.421738,0.083630,49,1,"{'n_neighbors': 49, 'p': 1}",0.916317,0.910291,0.919892,0.915500,0.003962,4
49,0.036445,0.019481,0.437359,0.058444,49,2,"{'n_neighbors': 49, 'p': 2}",0.916317,0.909091,0.919592,0.915000,0.004387,16

In [69]:
clf.best_params_

{'n_neighbors': 47, 'p': 1}

In [70]:
clf.score(X_train,y_train), clf.score(X_test, y_test)

(0.9210447761194029, 0.9130303030303031)